# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sampleapi:
    image: sampleapi
    build:
      context: .
      dockerfile: src/API/Sample.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5211:5211
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
