# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sampleapi:
    image: sampleapi
    build:
      context: .
      dockerfile: src/API/Sample.API/Dockerfile
    ports:
      - 5211:5211
    networks:
      - sampleApiNetwork
    depends_on:
      migrations:
        condition: service_healthy

  database:
    image: postgres
    # restart: always
    ports:
      - 5433:5432
    networks:
      - sampleApiNetwork
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_database

  migrations:
    build:
      context: .
      dockerfile: src/API/Sample.API/Dockerfile
    networks:
      - sampleApiNetwork
    depends_on:
      - database
    command: ["./wait-for-db-and-migrate.sh", "dotnet", "ef", "database", "update"]
    healthcheck:
      test: ["CMD-SHELL", "[ $$(psql -h db -U postgres -d test_database -c 'SELECT 1' >/dev/null 2>&1) $$? -eq 0 ]"]
      interval: 10s
      retries: 5

networks:
  sampleApiNetwork:
    driver: bridge