# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sampleapi:
    image: sampleapi
    build:
      context: .
      dockerfile: src/API/Sample.API/Dockerfile
    ports:
      - 8080:7020
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    ports:
      - 5433:5433
    environment:
      - POSTGRES_PASSWORD=postgres