// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sample.Persistence;

#nullable disable

namespace Sample.Persistence.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20240408185640_CreateTableInvoicingAddress")]
    partial class CreateTableInvoicingAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sample.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsStateRegistrationFree")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentClientId")
                        .HasColumnType("integer");

                    b.Property<string>("RegisteredNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateRegistration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClientId");

                    b.HasIndex("ParentClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Grupo AAAA",
                            Origin = "Origem",
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Grupo AAAA",
                            Type = "Grupo"
                        },
                        new
                        {
                            ClientId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Rede AAAA",
                            Origin = "Origem",
                            ParentClientId = 1,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Rede AAAA",
                            Type = "Rede"
                        },
                        new
                        {
                            ClientId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Parceiro  AAAA",
                            Origin = "Origem",
                            ParentClientId = 2,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Parceiro  AAAA",
                            Type = "Parceiro"
                        },
                        new
                        {
                            ClientId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  AAAA1",
                            Origin = "Origem",
                            ParentClientId = 3,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  AAAA1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  AAAA1",
                            Origin = "Origem",
                            ParentClientId = 3,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  AAAA1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 42,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Rede AAAB",
                            Origin = "Origem",
                            ParentClientId = 1,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Rede AAAB",
                            Type = "Rede"
                        },
                        new
                        {
                            ClientId = 43,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Parceiro  AAAB",
                            Origin = "Origem",
                            ParentClientId = 42,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Parceiro  AAAB",
                            Type = "Parceiro"
                        },
                        new
                        {
                            ClientId = 44,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  AAAB",
                            Origin = "Origem",
                            ParentClientId = 43,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  AAAB",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 45,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  AAAB",
                            Origin = "Origem",
                            ParentClientId = 43,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  AAAB",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Grupo BBBB",
                            Origin = "Origem",
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Grupo BBBB",
                            Type = "Grupo"
                        },
                        new
                        {
                            ClientId = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Rede BBBB",
                            Origin = "Origem",
                            ParentClientId = 6,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Rede BBBB",
                            Type = "Rede"
                        },
                        new
                        {
                            ClientId = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Parceiro  BBBB",
                            Origin = "Origem",
                            ParentClientId = 7,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Parceiro  BBBB",
                            Type = "Parceiro"
                        },
                        new
                        {
                            ClientId = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  BBBB1",
                            Origin = "Origem",
                            ParentClientId = 8,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  BBBB1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  BBBB1",
                            Origin = "Origem",
                            ParentClientId = 8,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  BBBB1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 47,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Parceiro  BBBC",
                            Origin = "Origem",
                            ParentClientId = 6,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Parceiro  BBBC",
                            Type = "Parceiro"
                        },
                        new
                        {
                            ClientId = 48,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  BBBC1",
                            Origin = "Origem",
                            ParentClientId = 47,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  BBBC1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 49,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  BBBC1",
                            Origin = "Origem",
                            ParentClientId = 47,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  BBBC1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 11,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Grupo CCCC",
                            Origin = "Origem",
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Grupo CCCC",
                            Type = "Grupo"
                        },
                        new
                        {
                            ClientId = 12,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Rede CCCC",
                            Origin = "Origem",
                            ParentClientId = 11,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Rede CCCC",
                            Type = "Rede"
                        },
                        new
                        {
                            ClientId = 13,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Parceiro  CCCC",
                            Origin = "Origem",
                            ParentClientId = 12,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Parceiro  CCCC",
                            Type = "Parceiro"
                        },
                        new
                        {
                            ClientId = 14,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  CCCC1",
                            Origin = "Origem",
                            ParentClientId = 13,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  CCCC1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 15,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  CCCC1",
                            Origin = "Origem",
                            ParentClientId = 13,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  CCCC1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 50,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Parceiro  CCCD",
                            Origin = "Origem",
                            ParentClientId = 12,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Parceiro  CCCD",
                            Type = "Parceiro"
                        },
                        new
                        {
                            ClientId = 51,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  CCCD1",
                            Origin = "Origem",
                            ParentClientId = 50,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  CCCD1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 52,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  CCCD1",
                            Origin = "Origem",
                            ParentClientId = 50,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  CCCD1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 16,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Grupo DDDD",
                            Origin = "Origem",
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Grupo DDDD",
                            Type = "Grupo"
                        },
                        new
                        {
                            ClientId = 17,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Rede DDDD",
                            Origin = "Origem",
                            ParentClientId = 16,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Rede DDDD",
                            Type = "Rede"
                        },
                        new
                        {
                            ClientId = 18,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Parceiro  DDDD",
                            Origin = "Origem",
                            ParentClientId = 17,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Parceiro  DDDD",
                            Type = "Parceiro"
                        },
                        new
                        {
                            ClientId = 19,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  DDDD1",
                            Origin = "Origem",
                            ParentClientId = 18,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  DDDD1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 20,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  DDDD1",
                            Origin = "Origem",
                            ParentClientId = 18,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  DDDD1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 53,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  DDDE1",
                            Origin = "Origem",
                            ParentClientId = 16,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  DDDE1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 54,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  DDDE1",
                            Origin = "Origem",
                            ParentClientId = 16,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  DDDE1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 21,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Grupo EEEE",
                            Origin = "Origem",
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Grupo EEEE",
                            Type = "Grupo"
                        },
                        new
                        {
                            ClientId = 22,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Rede EEEE",
                            Origin = "Origem",
                            ParentClientId = 21,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Rede EEEE",
                            Type = "Rede"
                        },
                        new
                        {
                            ClientId = 23,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Parceiro  EEEE",
                            Origin = "Origem",
                            ParentClientId = 22,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Parceiro  EEEE",
                            Type = "Parceiro"
                        },
                        new
                        {
                            ClientId = 24,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  EEEE1",
                            Origin = "Origem",
                            ParentClientId = 23,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  EEEE1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 25,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  EEEE1",
                            Origin = "Origem",
                            ParentClientId = 23,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  EEEE1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 26,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Rede AAA",
                            Origin = "Origem",
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Rede AAA",
                            Type = "Rede"
                        },
                        new
                        {
                            ClientId = 27,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Parceiro  AAA",
                            Origin = "Origem",
                            ParentClientId = 26,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Parceiro  AAA",
                            Type = "Parceiro"
                        },
                        new
                        {
                            ClientId = 28,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  AAA1",
                            Origin = "Origem",
                            ParentClientId = 27,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  AAA1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 29,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  AAA1",
                            Origin = "Origem",
                            ParentClientId = 27,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  AAA1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 30,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Rede BBB",
                            Origin = "Origem",
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Rede BBB",
                            Type = "Rede"
                        },
                        new
                        {
                            ClientId = 31,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Parceiro  BBB",
                            Origin = "Origem",
                            ParentClientId = 30,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Parceiro  BBB",
                            Type = "Parceiro"
                        },
                        new
                        {
                            ClientId = 32,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  BBB1",
                            Origin = "Origem",
                            ParentClientId = 31,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  BBB1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 33,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  BBB1",
                            Origin = "Origem",
                            ParentClientId = 31,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  BBB1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 34,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Parceiro  AA",
                            Origin = "Origem",
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Parceiro  AA",
                            Type = "Parceiro"
                        },
                        new
                        {
                            ClientId = 35,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  AA1",
                            Origin = "Origem",
                            ParentClientId = 34,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  AA1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 36,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  AA1",
                            Origin = "Origem",
                            ParentClientId = 34,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  AA1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 37,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Parceiro  BB",
                            Origin = "Origem",
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Parceiro  BB",
                            Type = "Parceiro"
                        },
                        new
                        {
                            ClientId = 38,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  BB1",
                            Origin = "Origem",
                            ParentClientId = 37,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  BB1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 39,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  BB1",
                            Origin = "Origem",
                            ParentClientId = 37,
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  BB1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 40,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  A1",
                            Origin = "Origem",
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  A1",
                            Type = "Hotel"
                        },
                        new
                        {
                            ClientId = 41,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyType = "REAL",
                            IsStateRegistrationFree = false,
                            Language = "BR",
                            LogoURL = "LogoURL",
                            Name = "Hotel  B1",
                            Origin = "Origem",
                            RegisteredNumber = "000",
                            StateRegistration = "00000",
                            TimeZone = "Brasilia",
                            TradeName = "Hotel  B1",
                            Type = "Hotel"
                        });
                });

            modelBuilder.Entity("Sample.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContactId"));

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ContactId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepartmentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Sample.Domain.Entities.InvoicingAddress", b =>
                {
                    b.Property<int>("InvoicingAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoicingAddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PostlCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.HasKey("InvoicingAddressId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("InvoicingAddress");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("OrderPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("OrderTotal")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Address", b =>
                {
                    b.HasOne("Sample.Domain.Entities.Client", "Client")
                        .WithOne("Address")
                        .HasForeignKey("Sample.Domain.Entities.Address", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Client", b =>
                {
                    b.HasOne("Sample.Domain.Entities.Client", "ParentClient")
                        .WithMany("ChildrenClient")
                        .HasForeignKey("ParentClientId");

                    b.Navigation("ParentClient");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Contact", b =>
                {
                    b.HasOne("Sample.Domain.Entities.Client", null)
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sample.Domain.Entities.Department", null)
                        .WithMany("Contacts")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sample.Domain.Entities.Event", b =>
                {
                    b.HasOne("Sample.Domain.Entities.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sample.Domain.Entities.InvoicingAddress", b =>
                {
                    b.HasOne("Sample.Domain.Entities.Client", "Client")
                        .WithOne("InvoicingAddres")
                        .HasForeignKey("Sample.Domain.Entities.InvoicingAddress", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Sample.Domain.Entities.Client", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ChildrenClient");

                    b.Navigation("Contacts");

                    b.Navigation("InvoicingAddres")
                        .IsRequired();
                });

            modelBuilder.Entity("Sample.Domain.Entities.Department", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
